### ISSUE TITLE
Error on validating permissions on self-managed deployment mode.

### ISSUE THREAD

**Issue by fernandoibm** [IBM/cp4d-deployment#101]
Hi, 

I'm following up a deployment using self-managed method, and even using an AWS user with AdministratorAccess policy attached, script fails to start the deployment saying that the AWS user does not have enough permissions.

**Here's the output:**
null_resource.permission_resource_validation[0]: Creating...
null_resource.permission_resource_validation[0]: Provisioning with 'local-exec'...
null_resource.permission_resource_validation[0] (local-exec): Executing: ["/bin/sh" "-c" "  chmod +x scripts/*.sh scripts/*.py\n  scripts/aws_permission_validation.sh ; if [ $? -ne 0 ] ; then echo \\\"Permission Verification Failed\\\" ; exit 1 ; fi\n  echo file | scripts/aws_resource_quota_validation.sh ; if [ $? -ne 0 ] ; then echo \\\"Resource Quota Validation Failed\\\" ; exit 1 ; fi\n"]
null_resource.permission_resource_validation[0] (local-exec): Create virtual python environment
null_resource.permission_resource_validation[0] (local-exec): Activate virtual python environment
null_resource.permission_resource_validation[0] (local-exec): Install required python modules in the virtual python environment
null_resource.permission_resource_validation[0]: Still creating... [10s elapsed]
null_resource.permission_resource_validation[0]: Still creating... [20s elapsed]
 
null_resource.permission_resource_validation[0] (local-exec): Cluster configuration
null_resource.permission_resource_validation[0] (local-exec): =====================
null_resource.permission_resource_validation[0] (local-exec):   The cluster configuration will be derived from terraform configuration: '/Users/<omitted>/g/rosas/prd/rosa4/selfmanaged-openshift/aws/scripts/../variables.tf'
 
null_resource.permission_resource_validation[0] (local-exec): {'region': sa-east-1'}
 
null_resource.permission_resource_validation[0] (local-exec): AWS access credentials need to be determined
null_resource.permission_resource_validation[0] (local-exec): ============================================
 
null_resource.permission_resource_validation[0] (local-exec):   Credentials taken from file.
 
 
null_resource.permission_resource_validation[0] (local-exec): Validate AWS configuration
null_resource.permission_resource_validation[0] (local-exec): ==========================
null_resource.permission_resource_validation[0] (local-exec):   Validation passed.
 
null_resource.permission_resource_validation[0] (local-exec): Going to check the permissions for user: <omitted>
null_resource.permission_resource_validation[0] (local-exec): The user <omitted> is member of the groups:
null_resource.permission_resource_validation[0] (local-exec): []
null_resource.permission_resource_validation[0] (local-exec): The following policies are applied to the user <omitted>:
null_resource.permission_resource_validation[0] (local-exec): ['AdministratorAccess']
null_resource.permission_resource_validation[0] (local-exec): Going to verify the permissions for the following resource actions:
null_resource.permission_resource_validation[0] (local-exec): ec2:AllocateAddress
null_resource.permission_resource_validation[0] (local-exec): ec2:AssociateAddress
null_resource.permission_resource_validation[0] (local-exec): ec2:AuthorizeSecurityGroupEgress
null_resource.permission_resource_validation[0] (local-exec): ec2:AuthorizeSecurityGroupIngress
null_resource.permission_resource_validation[0] (local-exec): ec2:CopyImage
null_resource.permission_resource_validation[0] (local-exec): ec2:CreateNetworkInterface
null_resource.permission_resource_validation[0] (local-exec): ec2:CreateSecurityGroup
null_resource.permission_resource_validation[0] (local-exec): ec2:CreateTags
null_resource.permission_resource_validation[0] (local-exec): ec2:CreateVolume
null_resource.permission_resource_validation[0] (local-exec): ec2:DeleteSecurityGroup
null_resource.permission_resource_validation[0] (local-exec): ec2:DeleteSnapshot
null_resource.permission_resource_validation[0] (local-exec): ec2:DeregisterImage
null_resource.permission_resource_validation[0] (local-exec): ec2:DescribeAccountAttributes
null_resource.permission_resource_validation[0] (local-exec): ec2:DescribeAddresses
null_resource.permission_resource_validation[0] (local-exec): ec2:DescribeAvailabilityZones
null_resource.permission_resource_validation[0] (local-exec): ec2:DescribeDhcpOptions
null_resource.permission_resource_validation[0] (local-exec): ec2:DescribeImages
null_resource.permission_resource_validation[0] (local-exec): ec2:DescribeInstanceAttribute
null_resource.permission_resource_validation[0] (local-exec): ec2:DescribeInstanceCreditSpecifications
null_resource.permission_resource_validation[0] (local-exec): ec2:DescribeInstances
null_resource.permission_resource_validation[0] (local-exec): ec2:DescribeInternetGateways
null_resource.permission_resource_validation[0] (local-exec): ec2:DescribeKeyPairs
null_resource.permission_resource_validation[0] (local-exec): ec2:DescribeNatGateways
null_resource.permission_resource_validation[0] (local-exec): ec2:DescribeNetworkAcls
null_resource.permission_resource_validation[0] (local-exec): ec2:DescribeNetworkInterfaces
null_resource.permission_resource_validation[0] (local-exec): ec2:DescribePrefixLists
null_resource.permission_resource_validation[0] (local-exec): ec2:DescribeRegions
null_resource.permission_resource_validation[0] (local-exec): ec2:DescribeRouteTables
null_resource.permission_resource_validation[0] (local-exec): ec2:DescribeSecurityGroups
null_resource.permission_resource_validation[0] (local-exec): ec2:DescribeSubnets
null_resource.permission_resource_validation[0] (local-exec): ec2:DescribeTags
null_resource.permission_resource_validation[0] (local-exec): ec2:DescribeVolumes
null_resource.permission_resource_validation[0] (local-exec): ec2:DescribeVpcAttribute
null_resource.permission_resource_validation[0] (local-exec): ec2:DescribeVpcClassicLink
null_resource.permission_resource_validation[0] (local-exec): ec2:DescribeVpcClassicLinkDnsSupport
null_resource.permission_resource_validation[0] (local-exec): ec2:DescribeVpcEndpoints
null_resource.permission_resource_validation[0] (local-exec): ec2:DescribeVpcs
null_resource.permission_resource_validation[0] (local-exec): ec2:ModifyInstanceAttribute
null_resource.permission_resource_validation[0] (local-exec): ec2:ModifyNetworkInterfaceAttribute
null_resource.permission_resource_validation[0] (local-exec): ec2:ReleaseAddress
null_resource.permission_resource_validation[0] (local-exec): ec2:RevokeSecurityGroupEgress
null_resource.permission_resource_validation[0] (local-exec): ec2:RevokeSecurityGroupIngress
null_resource.permission_resource_validation[0] (local-exec): ec2:RunInstances
null_resource.permission_resource_validation[0] (local-exec): ec2:TerminateInstances
null_resource.permission_resource_validation[0] (local-exec): ec2:AssociateDhcpOptions
null_resource.permission_resource_validation[0] (local-exec): ec2:AssociateRouteTable
null_resource.permission_resource_validation[0] (local-exec): ec2:AttachInternetGateway
null_resource.permission_resource_validation[0] (local-exec): ec2:CreateDhcpOptions
null_resource.permission_resource_validation[0] (local-exec): ec2:CreateInternetGateway
null_resource.permission_resource_validation[0] (local-exec): ec2:CreateNatGateway
null_resource.permission_resource_validation[0] (local-exec): ec2:CreateRoute
null_resource.permission_resource_validation[0] (local-exec): ec2:CreateRouteTable
null_resource.permission_resource_validation[0] (local-exec): ec2:CreateSubnet
null_resource.permission_resource_validation[0] (local-exec): ec2:CreateVpc
null_resource.permission_resource_validation[0] (local-exec): ec2:CreateVpcEndpoint
null_resource.permission_resource_validation[0] (local-exec): ec2:ModifySubnetAttribute
null_resource.permission_resource_validation[0] (local-exec): ec2:ModifyVpcAttribute
null_resource.permission_resource_validation[0] (local-exec): elasticloadbalancing:AddTags
null_resource.permission_resource_validation[0] (local-exec): elasticloadbalancing:ApplySecurityGroupsToLoadBalancer
null_resource.permission_resource_validation[0] (local-exec): elasticloadbalancing:AttachLoadBalancerToSubnets
null_resource.permission_resource_validation[0] (local-exec): elasticloadbalancing:ConfigureHealthCheck
null_resource.permission_resource_validation[0] (local-exec): elasticloadbalancing:CreateListener
null_resource.permission_resource_validation[0] (local-exec): elasticloadbalancing:CreateLoadBalancer
null_resource.permission_resource_validation[0] (local-exec): elasticloadbalancing:CreateLoadBalancerListeners
null_resource.permission_resource_validation[0] (local-exec): elasticloadbalancing:CreateTargetGroup
null_resource.permission_resource_validation[0] (local-exec): elasticloadbalancing:DeleteLoadBalancer
null_resource.permission_resource_validation[0] (local-exec): elasticloadbalancing:DeregisterInstancesFromLoadBalancer
null_resource.permission_resource_validation[0] (local-exec): elasticloadbalancing:DeregisterTargets
null_resource.permission_resource_validation[0] (local-exec): elasticloadbalancing:DescribeInstanceHealth
null_resource.permission_resource_validation[0] (local-exec): elasticloadbalancing:DescribeListeners
null_resource.permission_resource_validation[0] (local-exec): elasticloadbalancing:DescribeLoadBalancerAttributes
null_resource.permission_resource_validation[0] (local-exec): elasticloadbalancing:DescribeLoadBalancers
null_resource.permission_resource_validation[0] (local-exec): elasticloadbalancing:DescribeTags
null_resource.permission_resource_validation[0] (local-exec): elasticloadbalancing:DescribeTargetGroupAttributes
null_resource.permission_resource_validation[0] (local-exec): elasticloadbalancing:DescribeTargetHealth
null_resource.permission_resource_validation[0] (local-exec): elasticloadbalancing:ModifyLoadBalancerAttributes
null_resource.permission_resource_validation[0] (local-exec): elasticloadbalancing:ModifyTargetGroup
null_resource.permission_resource_validation[0] (local-exec): elasticloadbalancing:ModifyTargetGroupAttributes
null_resource.permission_resource_validation[0] (local-exec): elasticloadbalancing:RegisterInstancesWithLoadBalancer
null_resource.permission_resource_validation[0] (local-exec): elasticloadbalancing:RegisterTargets
null_resource.permission_resource_validation[0] (local-exec): elasticloadbalancing:SetLoadBalancerPoliciesOfListener
null_resource.permission_resource_validation[0] (local-exec): iam:AddRoleToInstanceProfile
null_resource.permission_resource_validation[0] (local-exec): iam:CreateInstanceProfile
null_resource.permission_resource_validation[0] (local-exec): iam:CreateRole
null_resource.permission_resource_validation[0] (local-exec): iam:DeleteInstanceProfile
null_resource.permission_resource_validation[0] (local-exec): iam:DeleteRole
null_resource.permission_resource_validation[0] (local-exec): iam:DeleteRolePolicy
null_resource.permission_resource_validation[0] (local-exec): iam:GetInstanceProfile
null_resource.permission_resource_validation[0] (local-exec): iam:GetRole
null_resource.permission_resource_validation[0] (local-exec): iam:GetRolePolicy
null_resource.permission_resource_validation[0] (local-exec): iam:GetUser
null_resource.permission_resource_validation[0] (local-exec): iam:ListInstanceProfilesForRole
null_resource.permission_resource_validation[0] (local-exec): iam:ListRoles
null_resource.permission_resource_validation[0] (local-exec): iam:ListUsers
null_resource.permission_resource_validation[0] (local-exec): iam:PassRole
null_resource.permission_resource_validation[0] (local-exec): iam:PutRolePolicy
null_resource.permission_resource_validation[0] (local-exec): iam:RemoveRoleFromInstanceProfile
null_resource.permission_resource_validation[0] (local-exec): iam:SimulatePrincipalPolicy
null_resource.permission_resource_validation[0] (local-exec): iam:TagRole
null_resource.permission_resource_validation[0] (local-exec): route53:ChangeResourceRecordSets
null_resource.permission_resource_validation[0] (local-exec): route53:ChangeTagsForResource
null_resource.permission_resource_validation[0] (local-exec): route53:CreateHostedZone
null_resource.permission_resource_validation[0] (local-exec): route53:DeleteHostedZone
null_resource.permission_resource_validation[0] (local-exec): route53:GetChange
null_resource.permission_resource_validation[0] (local-exec): route53:GetHostedZone
null_resource.permission_resource_validation[0] (local-exec): route53:ListHostedZones
null_resource.permission_resource_validation[0] (local-exec): route53:ListHostedZonesByName
null_resource.permission_resource_validation[0] (local-exec): route53:ListResourceRecordSets
null_resource.permission_resource_validation[0] (local-exec): route53:ListTagsForResource
null_resource.permission_resource_validation[0] (local-exec): route53:UpdateHostedZoneComment
null_resource.permission_resource_validation[0] (local-exec): s3:CreateBucket
null_resource.permission_resource_validation[0] (local-exec): s3:DeleteBucket
null_resource.permission_resource_validation[0] (local-exec): s3:GetAccelerateConfiguration
null_resource.permission_resource_validation[0] (local-exec): s3:GetBucketCors
null_resource.permission_resource_validation[0] (local-exec): s3:GetBucketLocation
null_resource.permission_resource_validation[0] (local-exec): s3:GetBucketLogging
null_resource.permission_resource_validation[0] (local-exec): s3:GetBucketObjectLockConfiguration
null_resource.permission_resource_validation[0] (local-exec): s3:GetBucketReplication
null_resource.permission_resource_validation[0] (local-exec): s3:GetBucketRequestPayment
null_resource.permission_resource_validation[0] (local-exec): s3:GetBucketTagging
null_resource.permission_resource_validation[0] (local-exec): s3:GetBucketVersioning
null_resource.permission_resource_validation[0] (local-exec): s3:GetBucketWebsite
null_resource.permission_resource_validation[0] (local-exec): s3:GetEncryptionConfiguration
null_resource.permission_resource_validation[0] (local-exec): s3:GetLifecycleConfiguration
null_resource.permission_resource_validation[0] (local-exec): s3:GetReplicationConfiguration
null_resource.permission_resource_validation[0] (local-exec): s3:ListBucket
null_resource.permission_resource_validation[0] (local-exec): s3:PutBucketAcl
null_resource.permission_resource_validation[0] (local-exec): s3:PutBucketTagging
null_resource.permission_resource_validation[0] (local-exec): s3:PutEncryptionConfiguration
null_resource.permission_resource_validation[0] (local-exec): s3:DeleteObject
null_resource.permission_resource_validation[0] (local-exec): s3:GetObject
null_resource.permission_resource_validation[0] (local-exec): s3:GetObjectAcl
null_resource.permission_resource_validation[0] (local-exec): s3:GetObjectTagging
null_resource.permission_resource_validation[0] (local-exec): s3:GetObjectVersion
null_resource.permission_resource_validation[0] (local-exec): s3:PutObject
null_resource.permission_resource_validation[0] (local-exec): s3:PutObjectAcl
null_resource.permission_resource_validation[0] (local-exec): s3:PutObjectTagging
null_resource.permission_resource_validation[0] (local-exec): autoscaling:DescribeAutoScalingGroups
null_resource.permission_resource_validation[0] (local-exec): ec2:DeleteNetworkInterface
null_resource.permission_resource_validation[0] (local-exec): ec2:DeleteVolume
null_resource.permission_resource_validation[0] (local-exec): elasticloadbalancing:DeleteTargetGroup
null_resource.permission_resource_validation[0] (local-exec): elasticloadbalancing:DescribeTargetGroups
null_resource.permission_resource_validation[0] (local-exec): iam:ListInstanceProfiles
null_resource.permission_resource_validation[0] (local-exec): iam:ListRolePolicies
null_resource.permission_resource_validation[0] (local-exec): iam:ListUserPolicies
null_resource.permission_resource_validation[0] (local-exec): s3:DeleteObject
null_resource.permission_resource_validation[0] (local-exec): tag:GetResources
null_resource.permission_resource_validation[0] (local-exec): ec2:DeleteDhcpOptions
null_resource.permission_resource_validation[0] (local-exec): ec2:DeleteInternetGateway
null_resource.permission_resource_validation[0] (local-exec): ec2:DeleteNatGateway
null_resource.permission_resource_validation[0] (local-exec): ec2:DeleteRoute
null_resource.permission_resource_validation[0] (local-exec): ec2:DeleteRouteTable
null_resource.permission_resource_validation[0] (local-exec): ec2:DeleteSubnet
null_resource.permission_resource_validation[0] (local-exec): ec2:DeleteVpc
null_resource.permission_resource_validation[0] (local-exec): ec2:DeleteVpcEndpoints
null_resource.permission_resource_validation[0] (local-exec): ec2:DetachInternetGateway
null_resource.permission_resource_validation[0] (local-exec): ec2:DisassociateRouteTable
null_resource.permission_resource_validation[0] (local-exec): ec2:ReplaceRouteTableAssociation
null_resource.permission_resource_validation[0] (local-exec): iam:CreateAccessKey
null_resource.permission_resource_validation[0] (local-exec): iam:CreateUser
null_resource.permission_resource_validation[0] (local-exec): iam:DeleteAccessKey
null_resource.permission_resource_validation[0] (local-exec): iam:DeleteUser
null_resource.permission_resource_validation[0] (local-exec): iam:DeleteUserPolicy
null_resource.permission_resource_validation[0] (local-exec): iam:GetUserPolicy
null_resource.permission_resource_validation[0] (local-exec): iam:ListAccessKeys
null_resource.permission_resource_validation[0] (local-exec): iam:PutUserPolicy
null_resource.permission_resource_validation[0] (local-exec): iam:TagUser
null_resource.permission_resource_validation[0] (local-exec): iam:GetUserPolicy
null_resource.permission_resource_validation[0] (local-exec): iam:ListAccessKeys
null_resource.permission_resource_validation[0] (local-exec): s3:PutBucketPublicAccessBlock
null_resource.permission_resource_validation[0] (local-exec): s3:GetBucketPublicAccessBlock
null_resource.permission_resource_validation[0] (local-exec): s3:PutLifecycleConfiguration
null_resource.permission_resource_validation[0] (local-exec): s3:HeadBucket
null_resource.permission_resource_validation[0] (local-exec): s3:ListBucketMultipartUploads
null_resource.permission_resource_validation[0] (local-exec): s3:AbortMultipartUpload
 
null_resource.permission_resource_validation[0] (local-exec):  * The user <omitted> has unsufficient permissions to exexute the following actions:
null_resource.permission_resource_validation[0] (local-exec): autoscaling:DescribeAutoScalingGroups
null_resource.permission_resource_validation[0] (local-exec): ec2:AssociateAddress
null_resource.permission_resource_validation[0] (local-exec): ec2:AttachInternetGateway
null_resource.permission_resource_validation[0] (local-exec): ec2:AuthorizeSecurityGroupEgress
null_resource.permission_resource_validation[0] (local-exec): ec2:CreateInternetGateway
null_resource.permission_resource_validation[0] (local-exec): ec2:CreateNatGateway
null_resource.permission_resource_validation[0] (local-exec): ec2:CreateNetworkInterface
null_resource.permission_resource_validation[0] (local-exec): ec2:CreateRoute
null_resource.permission_resource_validation[0] (local-exec): ec2:CreateSecurityGroup
null_resource.permission_resource_validation[0] (local-exec): ec2:CreateSubnet
null_resource.permission_resource_validation[0] (local-exec): ec2:CreateTags
null_resource.permission_resource_validation[0] (local-exec): ec2:CreateVolume
null_resource.permission_resource_validation[0] (local-exec): ec2:CreateVpc
null_resource.permission_resource_validation[0] (local-exec): ec2:CreateVpcEndpoint
null_resource.permission_resource_validation[0] (local-exec): ec2:DeleteInternetGateway
null_resource.permission_resource_validation[0] (local-exec): ec2:DeleteNetworkInterface
null_resource.permission_resource_validation[0] (local-exec): ec2:DeleteSubnet
null_resource.permission_resource_validation[0] (local-exec): ec2:DeleteVpcEndpoints
null_resource.permission_resource_validation[0] (local-exec): ec2:DeregisterImage
null_resource.permission_resource_validation[0] (local-exec): ec2:DescribeAvailabilityZones
null_resource.permission_resource_validation[0] (local-exec): ec2:DescribeImages
null_resource.permission_resource_validation[0] (local-exec): ec2:DescribeInstances
null_resource.permission_resource_validation[0] (local-exec): ec2:DescribeInternetGateways
null_resource.permission_resource_validation[0] (local-exec): ec2:DescribeNatGateways
null_resource.permission_resource_validation[0] (local-exec): ec2:DescribeRouteTables
null_resource.permission_resource_validation[0] (local-exec): ec2:DescribeSecurityGroups
null_resource.permission_resource_validation[0] (local-exec): ec2:DescribeSubnets
null_resource.permission_resource_validation[0] (local-exec): ec2:DescribeVpcAttribute
null_resource.permission_resource_validation[0] (local-exec): ec2:DescribeVpcClassicLink
null_resource.permission_resource_validation[0] (local-exec): ec2:DescribeVpcClassicLinkDnsSupport
null_resource.permission_resource_validation[0] (local-exec): ec2:RunInstances
null_resource.permission_resource_validation[0] (local-exec): elasticloadbalancing:ApplySecurityGroupsToLoadBalancer
null_resource.permission_resource_validation[0] (local-exec): elasticloadbalancing:AttachLoadBalancerToSubnets
null_resource.permission_resource_validation[0] (local-exec): elasticloadbalancing:ConfigureHealthCheck
null_resource.permission_resource_validation[0] (local-exec): elasticloadbalancing:CreateListener
null_resource.permission_resource_validation[0] (local-exec): elasticloadbalancing:CreateLoadBalancerListeners
null_resource.permission_resource_validation[0] (local-exec): elasticloadbalancing:CreateTargetGroup
null_resource.permission_resource_validation[0] (local-exec): elasticloadbalancing:DeregisterInstancesFromLoadBalancer
null_resource.permission_resource_validation[0] (local-exec): elasticloadbalancing:DescribeListeners
null_resource.permission_resource_validation[0] (local-exec): elasticloadbalancing:DescribeLoadBalancerAttributes
null_resource.permission_resource_validation[0] (local-exec): elasticloadbalancing:DescribeLoadBalancers
null_resource.permission_resource_validation[0] (local-exec): elasticloadbalancing:DescribeTargetHealth
null_resource.permission_resource_validation[0] (local-exec): elasticloadbalancing:ModifyLoadBalancerAttributes
null_resource.permission_resource_validation[0] (local-exec): elasticloadbalancing:ModifyTargetGroupAttributes
null_resource.permission_resource_validation[0] (local-exec): elasticloadbalancing:RegisterInstancesWithLoadBalancer
null_resource.permission_resource_validation[0] (local-exec): elasticloadbalancing:SetLoadBalancerPoliciesOfListener
null_resource.permission_resource_validation[0] (local-exec): iam:DeleteUser
null_resource.permission_resource_validation[0] (local-exec): s3:AbortMultipartUpload
null_resource.permission_resource_validation[0] (local-exec): s3:DeleteObject
null_resource.permission_resource_validation[0] (local-exec): s3:GetBucketCors
null_resource.permission_resource_validation[0] (local-exec): s3:GetBucketLocation
null_resource.permission_resource_validation[0] (local-exec): s3:GetBucketLogging
null_resource.permission_resource_validation[0] (local-exec): s3:GetBucketPublicAccessBlock
null_resource.permission_resource_validation[0] (local-exec): s3:GetBucketReplication
null_resource.permission_resource_validation[0] (local-exec): s3:GetBucketRequestPayment
null_resource.permission_resource_validation[0] (local-exec): s3:GetBucketTagging
null_resource.permission_resource_validation[0] (local-exec): s3:GetBucketVersioning
null_resource.permission_resource_validation[0] (local-exec): s3:GetEncryptionConfiguration
null_resource.permission_resource_validation[0] (local-exec): s3:GetLifecycleConfiguration
null_resource.permission_resource_validation[0] (local-exec): s3:GetObject
null_resource.permission_resource_validation[0] (local-exec): s3:GetObjectAcl
null_resource.permission_resource_validation[0] (local-exec): s3:GetObjectTagging
null_resource.permission_resource_validation[0] (local-exec): s3:GetObjectVersion
null_resource.permission_resource_validation[0] (local-exec): s3:GetReplicationConfiguration
null_resource.permission_resource_validation[0] (local-exec): s3:HeadBucket
null_resource.permission_resource_validation[0] (local-exec): s3:ListBucketMultipartUploads
null_resource.permission_resource_validation[0] (local-exec): s3:PutBucketAcl
null_resource.permission_resource_validation[0] (local-exec): s3:PutBucketTagging
null_resource.permission_resource_validation[0] (local-exec): s3:PutEncryptionConfiguration
null_resource.permission_resource_validation[0] (local-exec): s3:PutObject
null_resource.permission_resource_validation[0] (local-exec): s3:PutObjectTagging
null_resource.permission_resource_validation[0] (local-exec): "Permission Verification Failed"

**Comment by prsahoo** [comment]
Hi @fernandoibm   From the error message, it looks like the user does not have certain amount of accesses that are needed to deploy the cluster.  Can you please ensure that the policy that is attached to the user has Full Access to All Resources for all service types ? 

You could use these two scripts to check whether pre-requisites are met, before proceeding with the deployment.

https://github.com/IBM/cp4d-deployment/blob/master/selfmanaged-openshift/aws/scripts/aws_permission_validation.sh
https://github.com/IBM/cp4d-deployment/blob/master/selfmanaged-openshift/aws/scripts/aws_resource_quota_validation.sh

**Comment by fernandoibm** [comment]
Hi,

Did you see that part of the code? This user has AdministratorAccess policy attached, so I believe that this user has all needed permissions to proceed this deployment.

null_resource.permission_resource_validation[0] (local-exec): The following policies are applied to the user FO097044:
null_resource.permission_resource_validation[0] (local-exec): ['AdministratorAccess']


From: prsahoo ***@***.***>
Date: Thursday, April 28, 2022 at 6:59 PM
To: IBM/cp4d-deployment ***@***.***>
Cc: Luiz Fernando Barros ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [IBM/cp4d-deployment] Error on validating permissions on self-managed deployment mode. (Issue #101)
Hi @fernandoibm From the error message, it looks like the user does not have certain amount of accesses that are needed to deploy the cluster. Can you please ensure that the policy that is attached to the user has Full Access to All Resources
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
ZjQcmQRYFpfptBannerEnd

Hi @fernandoibm<https://github.com/fernandoibm> From the error message, it looks like the user does not have certain amount of accesses that are needed to deploy the cluster. Can you please ensure that the policy that is attached to the user has Full Access to All Resources for all service types ?

You could use these two scripts to check whether pre-requisites are met, before proceeding with the deployment.

https://github.com/IBM/cp4d-deployment/blob/master/selfmanaged-openshift/aws/scripts/aws_permission_validation.sh<https://github.com/IBM/cp4d-deployment/blob/master/selfmanaged-openshift/aws/scripts/aws_permission_validation.sh>
https://github.com/IBM/cp4d-deployment/blob/master/selfmanaged-openshift/aws/scripts/aws_resource_quota_validation.sh<https://github.com/IBM/cp4d-deployment/blob/master/selfmanaged-openshift/aws/scripts/aws_resource_quota_validation.sh>

**Comment by prsahoo** [comment]
@fernandoibm    I agree that the 'AdministratorAccess' has been attached to the user.  But there could be a possibility that the AdministratorAccess policy might not have everything covered.   Also i see the user is not part of any groups.

 Can you please run the below commands to check the policy details ?

 aws iam get-policy --policy-arn arn:aws:iam::aws:policy/AdministratorAccess

The output of the above will tell what is the current version of the policy , and then use the below command to check what is included in the current version of the policy. 
 
 aws iam get-policy-version --policy-arn arn:aws:iam::aws:policy/AdministratorAccess --version-id <version-id>

**Comment by fernandoibm** [comment]
Please find the outputs ***@***.***>

**Comment by fernandoibm** [comment]
@prsahoo
![1](https://user-images.githubusercontent.com/92641843/166291379-2297df68-a440-41a3-a7d7-fbff13154c89.png)
![2](https://user-images.githubusercontent.com/92641843/166291392-9c4b67a5-44e2-42cd-8b78-7e56cf26054b.png)

**Comment by prsahoo** [comment]
This looks like there is issues with Openshift  4.x installation , when trying to install in a restricted AWS environment . 
 Please see  https://access.redhat.com/solutions/5211941

So, we are suggesting to try with the `credentialsMode: Mint` . We need to add this after line 4 in this file https://github.com/IBM/cp4d-deployment/blob/master/selfmanaged-openshift/aws/ocp/templates.tf

**Comment by prsahoo** [comment]
Closing this issue as Installation was successful after using the Mint mode for installation.
