### ISSUE TITLE
Update diagram with storage and infra node details

### ISSUE THREAD

**Issue by smchamberlin** [IBM/cp4d-deployment#105]
Can we please update the diagram here:

https://github.com/IBM/cp4d-deployment/commits/master/managed-openshift/aws/terraform/images

to include details on the storage configuration for EFS/EBS and also infrastructure nodes?  (they may be dual-use "infra, worker" nodes).

Thanks

**Comment by shankarpentyala07** [comment]
Closing the issue as current available deployment is via marketplace
https://aws.amazon.com/marketplace/pp/prodview-xnyxvyyyjigue?sr=0-1&ref_=beagle&applicationId=AWSMPContessa
