### ISSUE TITLE
IBM Support

### ISSUE THREAD

**Issue by andresi12** [IBM/cp4d-deployment#107]
Hi, I would like to know is these Terraform scripts are IBM supported or if are entirely maintain by a open source community interested in CP4D. Thanks !

**Comment by anujsharma23** [comment]
@andresi12 : This is a packaged offering of Cloud Pak for Data - at present, the offering is available only via the marketplace. [Refer Read Me](https://github.com/IBM/cp4d-deployment#readme)

If you are not looking for a solution via the marketplace - Please use the product documentation [here](https://www.ibm.com/docs/en/cloud-paks/cp-data/4.6.x) for installation instrcutions.
