### ISSUE TITLE
Login to rosa cluster as cluster-admin. error: A server URL must be specified

### ISSUE THREAD

**Issue by barochiarg** [IBM/cp4d-deployment#108]
We are trying to install ROSA with CP4D services. Terraform went into error with below logs. We are seeing below continue messages since long. This issue is intermittent. When we check into "installer-files/.cred" file, cluster API url was missing.

_module.ocp.null_resource.configure_image_registry (local-exec):  Login to rosa cluster as cluster-admin
module.ocp.null_resource.configure_image_registry (local-exec): error: A server URL must be specified
module.ocp.null_resource.configure_image_registry: Still creating... [1m10s elapsed]
module.ocp.null_resource.configure_image_registry: Still creating... [1m20s elapsed]
module.ocp.null_resource.configure_image_registry: Still creating... [1m30s elapsed]
module.ocp.null_resource.configure_image_registry: Still creating... [1m40s elapsed]
module.ocp.null_resource.configure_image_registry: Still creating... [1m50s elapsed]
module.ocp.null_resource.configure_image_registry: Still creating... [2m0s elapsed]_

**Comment by SunilManika** [comment]
This issue was also reported by AWS team while they were testing Data Governance and Privacy with IBM Data Fabric from marketplace. 
https://aws.amazon.com/marketplace/pp/prodview-h6w2gbqgaihoa?sr=0-8&ref_=beagle&applicationId=AWSMPContessa
