### ISSUE TITLE
Issues with AWS Marketplace Offerings

### ISSUE THREAD

**Issue by Alan111S** [IBM/cp4d-deployment#116]
I noticed recently that this repo no longer has the selfmanaged-openshift\aws code and the Readme has been updated that "Cloud Pak for Data (any version) can be deployed on OCP" ... "Through the marketplace offerings on [Amazon Web Services]" etc.

Since I used to rely on your Terraform scripts quite heavily I made an attempt at using the Cloudformation templates for IBM Cloud Pak for Data - BYOL (https://aws.amazon.com/marketplace/pp/prodview-xnyxvyyyjigue?sr=0-1&ref_=beagle&applicationId=AWSMPContessa) to build a cluster on AWS and then install DataStage.

I had 2 issues with the build:-

1) The admin user was disabled after the CP4D install. I used the following to re-enable it:-
`export NAMESPACE=dm
  oc exec -it -n $NAMESPACE  $(oc get pod -n $NAMESPACE  -l component=usermgmt | tail -1 | cut -f1 -d\ ) -- bash -c "/usr/src/server-src/scripts/manage-user.sh --enable-user admin"`

2) While installing DataStage after the Cluster was setup, it was failing to pull an image `dsx-requisite-pre-install-job` with `ImagePullBackOff` state, so I had to update the global image pull secret to enable the cluster to pull images from the IBM Entitled Registry:-
`cpd-cli manage add-icr-cred-to-global-pull-secret ${IBM_ENTITLEMENT_KEY}`

**Comment by shankarpentyala07** [comment]
Hi @Alan111S ,
Thanks for bringing this up, Regarding the issues.
1. The  cloud pak for data admin user password is similar to openshift user password. The info is in the user guide:
https://ibm-mkpl-cp4d.s3.amazonaws.com/ibm-cloud-pak-for-data-on-aws-marketplace.pdf

<img width="740" alt="Screenshot 2023-04-05 at 1 10 51 PM" src="https://user-images.githubusercontent.com/25217700/230199028-473ad57a-a977-411f-b919-58a0e06021ef.png">

2. Regarding the datastage - we do have seperate marketplace offering:
https://aws.amazon.com/marketplace/pp/prodview-s42oa5unsg3tu?sr=0-2&ref_=beagle&applicationId=AWSMPContessa
and also the ImagePullBackOff error is not expected , could you please share the install log from the s3 bucket to review.

cc: @anujsharma23

**Comment by Alan111S** [comment]
Hi @shankarpentyala07 

Regarding the first issue, I can get the initial admin password of the cluster either by:-
`oc extract secret/admin-user-details --keys=initial_admin_password --to=-` or `cpd-cli manage get-cpd-instance-details --cpd_instance_ns=dm --get_admin_initial_credentials=true`

That is not the problem. The problem is that I'm unable to login to the CP4D Web Interface because the admin user is _**Disabled**_. The error I get is something Incorrect user or password. I spent a long time messing with passwords before I finally realised the admin user was not enabled.

I have to run a command to specifically enable the admin user, like this:- ` export NAMESPACE=dm
  oc exec -it -n $NAMESPACE  $(oc get pod -n $NAMESPACE  -l component=usermgmt | tail -1 | cut -f1 -d\ ) -- bash -c "/usr/src/server-src/scripts/manage-user.sh --enable-user admin"`

Then it works

**Comment by Alan111S** [comment]
Thanks for the info re DataStage being a seperate Marketplace offering - I didn't realise that.

Regards the second issue - it's not really a DataStage problem.

The problem is because a pre-requisite step for installing Cloudpak mentioned in Item Number 7 [Updating the global image pull secret](https://www.ibm.com/docs/en/SSQNUZ_4.6.x/cpd/install/prep-cluster-global-image-pull-secret.html) https://www.ibm.com/docs/en/cloud-paks/cp-data/4.6.x?topic=installing-preparing-your-cluster is not being performed by your scripts.

**Comment by Alan111S** [comment]
One more thing - I looked at the Cloudformation template for DataStage on Marketplace https://aws.amazon.com/marketplace/pp/prodview-s42oa5unsg3tu

The link to the template for New VPC is pointing to the template for the Existing VPC. So there is nowhere to download the template for deploying to a new VPC.

**Comment by Alan111S** [comment]
Attaching Install Logs from S3 Bucket 
[cpd-trace.log](https://github.com/IBM/cp4d-deployment/files/11165281/cpd-trace.log)
[cpd-bootstrap.log](https://github.com/IBM/cp4d-deployment/files/11165283/cpd-bootstrap.log)

**Comment by shankarpentyala07** [comment]
> Hi @shankarpentyala07
> 
> Regarding the first issue, I can get the initial admin password of the cluster either by:- `oc extract secret/admin-user-details --keys=initial_admin_password --to=-` or `cpd-cli manage get-cpd-instance-details --cpd_instance_ns=dm --get_admin_initial_credentials=true`
> 
> That is not the problem. The problem is that I'm unable to login to the CP4D Web Interface because the admin user is _**Disabled**_. The error I get is something Incorrect user or password. I spent a long time messing with passwords before I finally realised the admin user was not enabled.
> 
> I have to run a command to specifically enable the admin user, like this:- ` export NAMESPACE=dm oc exec -it -n $NAMESPACE $(oc get pod -n $NAMESPACE -l component=usermgmt | tail -1 | cut -f1 -d\ ) -- bash -c "/usr/src/server-src/scripts/manage-user.sh --enable-user admin"`
> 
> Then it works

Hi @Alan111S , I did built a cluster and recheck , I was able to login to cloud pak for data using the openshift password .Could you please recheck .

> Thanks for the info re DataStage being a seperate Marketplace offering - I didn't realise that.
> 
> Regards the second issue - it's not really a DataStage problem.
> 
> The problem is because a pre-requisite step for installing Cloudpak mentioned in Item Number 7 Updating the global image pull secret from this page https://www.ibm.com/docs/en/cloud-paks/cp-data/4.6.x?topic=installing-preparing-your-cluster is not being performed by your scripts.

We do update global pulll-secret. From the bootstrap log , I see add-cred-to-global-pull-secret is executed. For reference , below is the log:

```
[0m[1mmodule.cpd[0].null_resource.login_cluster: Creation complete after 1m43s [id=2544093640001771114][0m
[0m[1mmodule.cpd[0].null_resource.configure_global_pull_secret[0]: Creating...[0m[0m
[0m[1mmodule.cpd[0].null_resource.configure_global_pull_secret[0]: Provisioning with 'local-exec'...[0m[0m
[0m[1mmodule.cpd[0].null_resource.configure_global_pull_secret[0] (local-exec):[0m [0m(output suppressed due to sensitive value in config)
[0m[1mmodule.cpd[0].null_resource.configure_global_pull_secret[0] (local-exec):[0m [0m(output suppressed due to sensitive value in config)
[0m[1mmodule.cpd[0].null_resource.configure_global_pull_secret[0] (local-exec):[0m [0m(output suppressed due to sensitive value in config)
[0m[1mmodule.cpd[0].null_resource.configure_global_pull_secret[0] (local-exec):[0m [0m(output suppressed due to sensitive value in config)
[0m[1mmodule.cpd[0].null_resource.configure_global_pull_secret[0] (local-exec):[0m [0m(output suppressed due to sensitive value in config)
[0m[1mmodule.cpd[0].null_resource.configure_global_pull_secret[0] (local-exec):[0m [0m(output suppressed due to sensitive value in config)
[0m[1mmodule.cpd[0].null_resource.configure_global_pull_secret[0] (local-exec):[0m [0m(output suppressed due to sensitive value in config)
[0m[1mmodule.cpd[0].null_resource.configure_global_pull_secret[0] (local-exec):[0m [0m(output suppressed due to sensitive value in config)
[0m[1mmodule.cpd[0].null_resource.configure_global_pull_secret[0] (local-exec):[0m [0m(output suppressed due to sensitive value in config)
[0m[1mmodule.cpd[0].null_resource.configure_global_pull_secret[0] (local-exec):[0m [0m(output suppressed due to sensitive value in config)
[0m[1mmodule.cpd[0].null_resource.configure_global_pull_secret[0] (local-exec):[0m [0m(output suppressed due to sensitive value in config)
[0m[1mmodule.cpd[0].null_resource.configure_global_pull_secret[0] (local-exec):[0m [0m(output suppressed due to sensitive value in config)
[0m[1mmodule.cpd[0].null_resource.configure_global_pull_secret[0]: Still creating... [10s elapsed][0m[0m
[0m[1mmodule.cpd[0].null_resource.configure_global_pull_secret[0]: Still creating... [20s elapsed][0m[0m
[0m[1mmodule.cpd[0].null_resource.configure_global_pull_secret[0]: Still creating... [30s elapsed][0m[0m
[0m[1mmodule.cpd[0].null_resource.configure_global_pull_secret[0]: Still creating... [40s elapsed][0m[0m
[0m[1mmodule.cpd[0].null_resource.configure_global_pull_secret[0]: Still creating... [50s elapsed][0m[0m
[0m[1mmodule.cpd[0].null_resource.configure_global_pull_secret[0]: Still creating... [1m0s elapsed][0m[0m
[0m[1mmodule.cpd[0].null_resource.configure_global_pull_secret[0]: Still creating... [1m10s elapsed][0m[0m
[0m[1mmodule.cpd[0].null_resource.configure_global_pull_secret[0]: Still creating... [1m20s elapsed][0m[0m
[0m[1mmodule.cpd[0].null_resource.configure_global_pull_secret[0]: Still creating... [1m30s elapsed][0m[0m
[0m[1mmodule.cpd[0].null_resource.configure_global_pull_secret[0]: Still creating... [1m40s elapsed][0m[0m
[0m[1mmodule.cpd[0].null_resource.configure_global_pull_secret[0]: Still creating... [1m50s elapsed][0m[0m
[0m[1mmodule.cpd[0].null_resource.configure_global_pull_secret[0]: Still creating... [2m0s elapsed][0m[0m
[0m[1mmodule.cpd[0].null_resource.configure_global_pull_secret[0]: Still creating... [2m10s elapsed][0m[0m
[0m[1mmodule.cpd[0].null_resource.configure_global_pull_secret[0]: Still creating... [2m20s elapsed][0m[0m
[0m[1mmodule.cpd[0].null_resource.configure_global_pull_secret[0]: Still creating... [2m30s elapsed][0m[0m
[0m[1mmodule.cpd[0].null_resource.configure_global_pull_secret[0]: Still creating... [2m40s elapsed][0m[0m
[0m[1mmodule.cpd[0].null_resource.configure_global_pull_secret[0]: Still creating... [2m50s elapsed][0m[0m
[0m[1mmodule.cpd[0].null_resource.configure_global_pull_secret[0]: Still creating... [3m0s elapsed][0m[0m
[0m[1mmodule.cpd[0].null_resource.configure_global_pull_secret[0]: Still creating... [3m10s elapsed][0m[0m
[0m[1mmodule.cpd[0].null_resource.configure_global_pull_secret[0]: Still creating... [3m20s elapsed][0m[0m
[0m[1mmodule.cpd[0].null_resource.configure_global_pull_secret[0]: Still creating... [3m30s elapsed][0m[0m
[0m[1mmodule.cpd[0].null_resource.configure_global_pull_secret[0]: Still creating... [3m40s elapsed][0m[0m
[0m[1mmodule.cpd[0].null_resource.configure_global_pull_secret[0]: Still creating... [3m50s elapsed][0m[0m
[0m[1mmodule.cpd[0].null_resource.configure_global_pull_secret[0]: Still creating... [4m0s elapsed][0m[0m
[0m[1mmodule.cpd[0].null_resource.configure_global_pull_secret[0]: Still creating... [4m10s elapsed][0m[0m
[0m[1mmodule.cpd[0].null_resource.configure_global_pull_secret[0]: Still creating... [4m20s elapsed][0m[0m
[0m[1mmodule.cpd[0].null_resource.configure_global_pull_secret[0]: Still creating... [4m30s elapsed][0m[0m
[0m[1mmodule.cpd[0].null_resource.configure_global_pull_secret[0]: Still creating... [4m40s elapsed][0m[0m
[0m[1mmodule.cpd[0].null_resource.configure_global_pull_secret[0]: Still creating... [4m50s elapsed][0m[0m
[0m[1mmodule.cpd[0].null_resource.configure_global_pull_secret[0]: Still creating... [5m0s elapsed][0m[0m
[0m[1mmodule.cpd[0].null_resource.configure_global_pull_secret[0]: Creation complete after 5m1s [id=4185688590919790730][0m
```

It would be helpful to view output of below command to prior datastage install

```
oc get secret/pull-secret \
  -n openshift-config \
  --template='{{index .data ".dockerconfigjson" | base64decode}}' 
```

> One more thing - I looked at the Cloudformation template for DataStage on Marketplace https://aws.amazon.com/marketplace/pp/prodview-s42oa5unsg3tu
> 
> The link to the template for New VPC is pointing to the template for the Existing VPC. So there is nowhere to download the template for deploying DataStage to a new VPC.

Thanks a lot for bringing this up. I will work with marketplace team to get it updated.

**Comment by Alan111S** [comment]
You said:- Hi @Alan111S , I did built a cluster and recheck , I was able to login to cloud pak for data using the openshift password .Could you please recheck .

I'm trying to login to here:- https://cpd-dm.apps.cp4d463.dm-cp4d-40.mettleci.cloud/zen/

Using username 'admin' and password obtained using:- 
`[root@ip-10-0-130-58 ec2-user]# oc extract secret/admin-user-details --keys=initial_admin_password --to=-                                         # initial_admin_password
lzywEqsHSN05
[root@ip-10-0-130-58 ec2-user]#
`
From the screenshot, you can see it is not working
<img width="1791" alt="Screenshot 2023-04-07 at 10 20 31 pm" src="https://user-images.githubusercontent.com/17717393/230607903-e16ac6cd-b69a-4e06-96e6-297a881bcfd3.png">

**Comment by Alan111S** [comment]
Output from:- `oc get secret/pull-secret \
  -n openshift-config \
  --template='{{index .data ".dockerconfigjson" | base64decode}}' `
  
  `{
        "auths": {
                "cloud.openshift.com": {
                        "auth": "b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K2FsYW5wcm90aGVyb2RhdGFtaWdyYXRvcnNjb20xZHQ3dGRudmZxaXd2OXJ6eG1rdWNpaXRnZDc6TFVHUE5VW
                },
                "cp.icr.io": {
                        "auth": "YWxhbi5wcm90aGVyb0BpYm0uY29tOmV5SmhiR2NpT2lKSVV6STFOaUo5LmV5SnBjM01pT2lKSlFrMGdUV0Z5YTJWMGNHeGhZMlVpTENKcFlYUWlPaV4dEJuMmdDZmM0X1NBS2tpbVpCQ21YZ25SN0ZyMDRSOXRmNV9B"
                },
                "quay.io": {
                        "auth": "b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K2FsYW5wcm90aGVyb2RhdGFtaWdyYXRvcnNjb20xZHQ3dGRudmZxaXd2OXJ6eG1rdWNpaXRnZDc6TFVHUE5VW
                },
                "registry.connect.redhat.com": {
                        "auth": "NTM0Nzk1NTF8dWhjLTFkVDdUZG5WRnFpd1Y5Ulp4bUt1Y0lJVEdENzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmhZVFV3TlRkaU5UWRqYzBHN2N0alVPMVA1b1dWcDhTRVBFMjZKVXRNR0NtSDNBeFlMT09ZZWhJYzAwelI1UXJHV3huNm1xMjRYSklGdHlFU1lqY0Q2NkI2QVBENWRPYWpWOE92TVY0UEozRlJwaWYwT3B3WFMwZk9tXR4Nnp5cXM1WmJCeEFVT19faVJ6SWVhd2ZJdW9HelByY0VHaHRNSkNyTDUyTnVXa1ZtRW5EcHRNVkxNZnZ5UzY3cmhLRktHNS1FR2RsNjJsUGxLeVJjaDZpUWFBOVFrQXdEZ2UwMzh5U2VSNzdby1UVWdpVHFaMUhJYV9LbVFvYnZHX1pScjFWU3ZDaTAzNmcxVGxBZWJhWEtMSFl1azI3VnpDTzBjUVJPVzU4OUFBcjJIcmNta0dGbjVFX08xMEMxWlV3ZlJ0QVRLNGQxWk03QlJsUXhuX3VqUU4OXR5cDFiOEVUX3F2ZHdvYTJtRTlGZUFTZHNSR3R2bjhETW1pYlpCYmhZZjNKelNNLUNhN05xNko2RThzbVAzX2NtbUVFUEVmZ1FkWGJtZ0Vra1ZJTQ=="
                },
                "registry.redhat.io": {
                        "auth": "NTM0Nzk1NTF8dWhjLTFkVDdUZG5WRnFpd1Y5Ulp4bUt1Y0lJVEdENzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmhZVFV3TlRkaU5UWRqYzBHN2N0alVPMVA1b1dWcDhTRVBFMjZKVXRNR0NtSDNBeFlMT09ZZWhJYzAwelI1UXJHV3huNm1xMjRYSklGdHlFU1lqY0Q2NkI2QVBENWRPYWpWOE92TVY0UEozRlJwaWYwT3B3WFMwZk9tXR4Nnp5cXM1WmJCeEFVT19faVJ6SWVhd2ZJdW9HelByY0VHaHRNSkNyTDUyTnVXa1ZtRW5EcHRNVkxNZnZ5UzY3cmhLRktHNS1FR2RsNjJsUGxLeVJjaDZpUWFBOVFrQXdEZ2UwMzh5U2VSNzdby1UVWdpVHFaMUhJYV9LbVFvYnZHX1pScjFWU3ZDaTAzNmcxVGxBZWJhWEtMSFl1azI3VnpDTzBjUVJPVzU4OUFBcjJIcmNta0dGbjVFX08xMEMxWlV3ZlJ0QVRLNGQxWk03QlJsUXhuX3VqUU4OXR5cDFiOEVUX3F2ZHdvYTJtRTlGZUFTZHNSR3R2bjhETW1pYlpCYmhZZjNKelNNLUNhN05xNko2RThzbVAzX2NtbUVFUEVmZ1FkWGJtZ0Vra1ZJTQ=="
`

**Comment by shankarpentyala07** [comment]
@Alan111S I have deleted the pull-secret output since it contains creds and I see the pull-secret has cp.icr.io registry creds updated in it.

The cloud pak for data password is same as your openshift password.Please try logging into cloud pak for data with openshift username password you supplied when creating stack.

This info can be also found from the outputs section in the stack.
Please refer step 6. Login to Cloud Pak for Data web client in below user gudie.
https://ibm-mkpl-cp4d.s3.amazonaws.com/ibm-cloud-pak-for-data-on-aws-marketplace.pdf

**Comment by Alan111S** [comment]
You wrote "The cloud pak for data password is same as your openshift password."

No, that's not correct. The openshift user I have set as "ocadmin" and I have set the password as a parameter in the CF template.

I can use the ocadmin user to login to the Openshift console here:- https://console-openshift-console.apps.cp4d463.dm-cp4d-40.mettleci.cloud/dashboards/
![0eb0f8fb-cb2f-4c16-a64f-bc3190a7f790](https://user-images.githubusercontent.com/17717393/230696797-60d035d4-f95a-4a72-937e-5bf65e80ccb2.png)

But I can't use ocadmin to login to https://cpd-dm.apps.cp4d463.dm-cp4d-40.mettleci.cloud/zen/ (see previous screenshot). You need to use 'admin' and get the initial admin password.

As far as I know, that has never been possible and I have built CP4D Versions 3.01, 3.5, 4.0, 4.01, 4.02 and 4.5 as well as this 4.6.3. 

If this is still unclear, maybe we can get on a webex after Easter so I can show you. Or if you believe it should work, you can show me !

**Comment by shankarpentyala07** [comment]
Sure - I will setup a webex meeting.
What I meant is cloud pak for data credentials are:
Username: admin
Password: same as openshift user ocsadmin password passed to the cft.

**Comment by Alan111S** [comment]
OK so I was able to login to https://cpd-dm.apps.cp4d463.dm-cp4d-40.mettleci.cloud/zen/
using username "admin" and the same password I set in the Cloudformation template for the Cluster admin "ocadmin"

**Comment by Alan111S** [comment]
> Thanks for the info re DataStage being a seperate Marketplace offering - I didn't realise that.
> 
> Regards the second issue - it's not really a DataStage problem.
> 
> The problem is because a pre-requisite step for installing Cloudpak mentioned in Item Number 7 Updating the global image pull secret from this page https://www.ibm.com/docs/en/cloud-paks/cp-data/4.6.x?topic=installing-preparing-your-cluster is not being performed by your scripts.

This turns out to be because I was using my IBM email address as the CPD API Username but it should be "cp".

**Comment by Alan111S** [comment]
@shankarpentyala07 Yes, sure.
