### ISSUE TITLE
Add support for DB2 Data Gate app in AWS

### ISSUE THREAD

**Issue by pelletierkevin** [IBM/cp4d-deployment#20]
Hi, 

We are the DB2 Data Gate team, a product running on Cloud Pak and generally available since June 19th. 

At the moment, we support IBM Cloud and we are investigating to get a personal AWS environment. We are willing to support AWS and Azure. For the moment we only want to focus on AWS.

The storage options we support are : 
- Network File System (NFS)
- Portworx
- Rook/Ceph
- hostPath storage (local)
- OCS (OpenShift Container Storage) (required storage class : ocs-storagecluster-cephfs (default)

As the current cp4d-deployment repo doesn't include DB2 Data Gate in the possible app to be installed using terraform I'm initiating this process with this issue. 

Forked cp4d-deployment repo with my branch adding Db2 Data Gate : https://github.com/pelletierkevin/cp4d-deployment/tree/pelletierkevin_datagate

**Comment by satyamodi** [comment]
We currently supports Portworx, OCS and EFS (which provides NFS file system for aws) in our terraform script for AWS. Rook/Ceph and hostPath storage (local) are not supported. Test end to end flow for all the changes made in the terraform scripts.

**Comment by ajiyos** [comment]
We will use the same issue for the build pipeline integration.

**Comment by ajiyos** [comment]
@sahutulika Please work with Kevin to create the pipeline. @pelletierkevin 
It should cover install and test verification of datagate terraform scripts over multiple storage classes.

**Comment by satyamodi** [comment]
DB2 Data Gate installation is added in terraform automation scripts.
