### ISSUE TITLE
AWS Credentials in osaws_var.tfvars.txt not used

### ISSUE THREAD

**Issue by Alan111S** [IBM/cp4d-deployment#23]
Despite populating the osaws_var.tfvars.txt with valid AWS credentials, I am getting this error message when I run:-

```
[root@ip-172-31-42-158 aws_infra]# terraform apply -var-file=/root/cp4d-deployment-master/aws/aws_infra/osaws_var.tfvars.txt
data.template_file.awscreds: Refreshing state...
data.template_file.repo: Refreshing state...
data.template_file.clusterautoscaler: Refreshing state...
data.template_file.awsregion: Refreshing state...
data.template_file.crio-mc: Refreshing state...
data.template_file.efs-configmap: Refreshing state...
data.template_file.registry-conf: Refreshing state...
data.template_file.security-limits-mc: Refreshing state...
data.template_file.sysctl-machineconfig: Refreshing state...
data.template_file.portworx-override: Refreshing state...
data.template_file.registry-mc: Refreshing state...

Error: No valid credential sources found for AWS Provider.
        Please see https://terraform.io/docs/providers/aws/index.html for more information on
        providing credentials for the AWS Provider

  on vpc.tf line 1, in provider "aws":
   1: provider "aws" {

```
I can work around this issue multiple ways. Personally, I have used /root/.aws/credentials file. But I thought it may be useful to you to know there is an issue. I tested this with terraform version 0.12.29

By the way, I also found I needed to use the latest version of terraform to work with your scripts. I suggest you add this to the documentation, so that it's clear. I spent some time chasing 'bugs' that were simply due to having an out of date terraform install.

**Comment by ajiyos** [comment]
@Alan111S  Thank you.

**Comment by shaithal** [comment]
@Alan111S  we acknowledge this issue. And update  you once the fix is available.

**Comment by satyamodi** [comment]
The issue is fixed and changes are pushed to the master branch.
