### ISSUE TITLE
Allow Cluster Network IP to be a variable in AWS config.

### ISSUE THREAD

**Issue by SionArtingstall** [IBM/cp4d-deployment#38]
In the install-config.yaml the cluster network is hardcoded at 10.128.0.0/16.  If you change the vpc and subnet variables in the aws config to something other than 10.0.0.0/16 then install fails due to overlapping cidr ranges.  Should be able to pass a variable through for the cluster network if changing the cidr and subnet variables.

**Comment by parthakom2** [comment]
@satyamodi @shaithal

**Comment by satyamodi** [comment]
new variable "cluster_network_cidr" is added in variable.tf file which can be used for passing network cidr.

**Comment by SionArtingstall** [comment]
Thanks for adding this :-)
