### ISSUE TITLE
Portworx licensing does not mention IBM Essentials option

### ISSUE THREAD

**Issue by aleks-mariusz** [IBM/cp4d-deployment#39]
I notice that the only option regarding Portworx licensing mentioned is the trial Enterprise license.  Portworx has as of CP4D version 2.5 worked out an option to allow the bundled entitlement license to be use which allows up to 8 nodes.

Is there a reason that the IBM Essentials version of the Portworx license does not appear in the ReadMe? It's fully supported on CP4D v3 (and has since v2.5).

**Comment by parthakom2** [comment]
@aleks-mariusz thanks for bringing this up. its a supported edition for CP4D that comes with the CP4D licensed entitlements. Its not listed in README as the terraform scripts does not currently have a hook to consume the IBM portworx package. It can be installed manually and used.

**Comment by aleks-mariusz** [comment]
Could we (on behalf of Portworx by whom i am employed with) request the README be updated to at least reflect that information, and just mention this is entitled license is a possibility just that it does not have terraform support but perhaps include also a link to [the official ibm docs](https://www.ibm.com/support/producthub/icpdata/docs/content/SSQNUZ_current/cpd/install/portworx-install.html) on this route?).

Our goal is to keep the user informed of the possibilities, and should they choose to go with the trial license it is an active choice rather than due to lack of awareness of alternative licensing models we currently have agreements with IBM in place on.

**Comment by Alan111S** [comment]
@aleks-mariusz Is there a possibility to install using the trial Enterprise license (utilising these scripts) and then switch to the IBM Essentials version?

**Comment by aleks-mariusz** [comment]
We don't have a license-migration path with this approach, the portworx software needs to be initialized with either a special step for portworx 2.3.1.1 (what cloudpak 2.5 came certified with) or with non-public images (these are downloaded from passport advantage) in the case of portworx 2.5+ (what cloudpak 3.0.x certified).  However i am happy to give you contact details of ibm engineers on the cp4d on Sriram's team who can walk you through the procedure and use the necessary scripts IBM has written and bundle for a BYOI (self-infra provided) software based installation.

**Comment by Alan111S** [comment]
Thanks for the information @aleks-mariusz . I'll bear that in mind - we are not using Portworx right now but I wanted to know for the future

**Comment by parthakom2** [comment]
Added the entitled portworx link https://github.com/IBM/cp4d-deployment/pull/41

**Comment by parthakom2** [comment]
portworx essentials is documented, closing this.

https://github.com/IBM/cp4d-deployment/blob/master/selfmanaged-openshift/aws/VARIABLES.md
