### ISSUE TITLE
Document that Elastic File System is a Technology Preview feature

### ISSUE THREAD

**Issue by thanusiak** [IBM/cp4d-deployment#43]
Based on OCP documentation:

Elastic File System is a Technology Preview feature only. Technology Preview features are not supported with Red Hat production service level agreements (SLAs) and might not be functionally complete. Red Hat does not recommend using them in production. These features provide early access to upcoming product features, enabling customers to test functionality and provide feedback during the development process.

https://docs.openshift.com/container-platform/4.3/storage/persistent_storage/persistent-storage-efs.html

CP4D users should be aware of this limitation 

The above applies to 4.x (all the way to 4.6 at the time of writing)

**Comment by satyamodi** [comment]
Changes merged to master branch.
