### ISSUE TITLE
Issue in the terraform destroy -target null_resource.destroy_cluster -var-file="Path To osaws_var.tfvars file" step

### ISSUE THREAD

**Issue by rharken** [IBM/cp4d-deployment#54]
When running the null_resource.destroy_cluster step - the process is unable to delete the 3 private subnets.
aws_subnet.private1[0]
aws_subnet.private2[0]
aws_subnet.private3[0]

terraform destroy process fails with timeout.

**Comment by satyamodi** [comment]
Issue was fixed in latest releases.
