### ISSUE TITLE
problem with terraform script

### ISSUE THREAD

**Issue by winchenbach** [IBM/cp4d-deployment#55]
While running "terraform apply" right after the portworx storage classes get created, I get the following error. This continually happens now if I try "terraform apply" again.  

Error: Error running command './reencrypt_route.sh cpd-tenant': exit status 1. Output: error: error executing jsonpath "_{.items[0].metadata.name}": Error executing template: array index out of bounds: index 0, length 0. Printing more information for debugging the template:
	template was:
		{.items[0].metadata.name}
	object given to jsonpath engine was:
		map[string]interface {}{"apiVersion":"v1", "items":[]interface {}{}, "kind":"List", "metadata":map[string]interface {}{"resourceVersion":"", "selfLink":""}}

error: filespec must match the canonical format: [[namespace/]pod:]file/path
Error from server (NotFound): routes.route.openshift.io "cpd-tenant-cpd" not found
error: open /cert.crt: no such file or directory
rm: cannot remove '/cert.crt': No such file or directory_

**Comment by shrumit** [comment]
Followed up internally. For future reference: this occurs when the variable `accept_cpd_license` has not been set to "yes".
