### ISSUE TITLE
Parameterize the ELB Timeout Value in AWS Script update-elb-timeout.sh

### ISSUE THREAD

**Issue by Alan111S** [IBM/cp4d-deployment#64]
It has been agreed that the ELB Timeout Value in update-elb-timeout.sh should be parameterized.

This is needed for Customers installing DataStage and using the Legacy DataStage Clients as well as for others that are installing Cognos.

In cpd-install.tf there is a script to setup the idle time
`"./update-elb-timeout.sh ${local.vpcid}"`

The affected line in update-elb-timeout.sh is:-
`aws elb modify-load-balancer-attributes --load-balancer-name $lbs --load-balancer-attributes "{\"ConnectionSettings\":{\"IdleTimeout\":600}}"`

At the moment the value defaults to 60 seconds and the script is hard coded to set it to 600 seconds but it sometimes needs to be set as high as 1800 or 3600 seconds. The maximum value allowed is 4000 seconds.

**Comment by satyamodi** [comment]
new variable added for configuring lb timeout value

variable "classic-lb-timeout" {
  description = "Classic loadbalancer timeout value in seconds."
  default = "600"
}
