### ISSUE TITLE
autocaler and efs script changes

### ISSUE THREAD

**Issue by satyamodi** [IBM/cp4d-deployment#65]
Parameterize
minReplicas = 1         
max-total-nodes     = 24
Append cluster id to efs security group name.

**Comment by shaithal** [comment]
min and maxReplicas in machine-autoscaler

**Comment by satyamodi** [comment]
New variables added
variable "autoscaler-replica-count" {
  description = "Replica count for machine autoscaler."
  default = "1"
}

variable "max-total-nodes" {
  description = "Maximum number of node count for cluster autoscaler."
  default = "24"
}

cluster id appended with efs security group name.
