### ISSUE TITLE
Azure: Terraform script az_resource_quota_validation.sh gets an error

### ISSUE THREAD

**Issue by wahl7** [IBM/cp4d-deployment#67]
cp4d-deployment/selfmanaged-openshift/azure/azure_infra/az_resource_quota_validation.sh 

When the Terraform script gets to calling the az_resource_quota_validation.sh bash script, I get the following error:

null_resource.az_validation_check: Destroying... [id=5051546956155078295]
null_resource.az_validation_check: Destruction complete after 0s
null_resource.az_validation_check: Creating...
null_resource.az_validation_check: Provisioning with 'local-exec'...
null_resource.az_validation_check (local-exec): Executing: ["cmd" "/C" "chmod +x ./*.sh"]
null_resource.az_validation_check: Provisioning with 'local-exec'...
null_resource.az_validation_check (local-exec): Executing: ["cmd" "/C" "./az_resource_quota_validation.sh -appId 41e92f4e-604f-4c99-868f-b9e9f50ac12a -password [redacted] -subscriptionId 57142dd5-0c01-43d2-aa2e-524391595206 -region canadacentral -printlog false -is_wsl no -is_wkc no -is_wml no -is_dv no -is_wos no -is_spark no -is_cde no -is_streams no -is_streams_flows no -is_db2wh no -is_ds no -is_db2oltp no -is_dods no -is_spss no -is_bigsql no -is_pa no -is_ca no ; if [ $? -ne 0 ] ; then echo \"Resource quota validation Failed\" ; exit 1 ; fi"]
null_resource.az_validation_check (local-exec): '.' is not recognized as an internal or external command,
null_resource.az_validation_check (local-exec): operable program or batch file.
 
Error: Error running command './az_resource_quota_validation.sh -appId 41e92f4e-604f-4c99-868f-b9e9f50ac12a -password [redacted] -tenantId 490a6c2b-9d4c-46e8-90c0-ab0dce6bcca0 -subscriptionId 57142dd5-0c01-43d2-aa2e-524391595206 -region canadacentral -printlog false -is_wsl no -is_wkc no -is_wml no -is_dv no -is_wos no -is_spark no -is_cde no -is_streams
no -is_streams_flows no -is_db2wh no -is_ds no -is_db2oltp no -is_dods no -is_spss no -is_bigsql no -is_pa no -is_ca no ; if [
$? -ne 0 ] ; then echo "Resource quota validation Failed" ; exit 1 ; fi': exit status 1. Output: '.' is not recognized as an internal or external command,
operable program or batch file.

I also get some errors trying to execute that bash script on it’s out without running ‘terraform apply’. I did populate the env variables in the env.sh bash script as well as all the variables that needed to be defined in the variables.tf file. I can confirm I have enough vCPU cores available in my Azure subscription for the DSv3 family series required. So don’t think it’s failing on the vCPU check, I think the script itself appears to be failing for some sort of syntax error. Please see output below running the az_resource_quota_validation.sh bash script by itself:
 
$ ./az_resource_quota_validation.sh
Total vcpu rquired is 40
 
**************************************************
List of values entered
**************************************************
 
The client_id entered is :
The client secret entered is :
The TENANT_ID value entered is:
The subscriptionId value entered is :
The location which has been selected is :        
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python39\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python39\lib\json\decoder.py", line 355, in raw_decode      
    raise JSONDecodeError("Expecting value", s, err.value) from None  
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
 
**************************************************
Executing curl command to get the usage data
**************************************************
 
The vCPU usage limit is written into the file : az_vcpu_limit_20210317-173323.json
 
**************************************************
Executing curl command to get the Network data
**************************************************
 
The Network usage limit is written into the file : az_network_limit_20210317-173323.json
 
****************************************************************************************************
Please find the default resource quota's required
As per the OCP4.5 documentation for azure, the minimum quota required are as follows:
****************************************************************************************************
Component                     Number of components required by default(minimum)
-----------------             ---------------------------------------------------
vCPU                          40
vNet                          1
Network Interfaces            6
Network security groups       2
Network load balancers        3
Public IP addresses           3
Private IP addresses          7
****************************************************************************************************
Summary of the resource quota details for the subscriptionId :
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Resource_name             |  Required                  |  Available                 |  Validation_check
-----------------------   |  -----------------------   |  -----------------------   |  -----------------------
awk: cmd. line:1: warning: regexp escape sequence `\"' is not a known regexp operator
awk: cmd. line:1: warning: regexp escape sequence `\,' is not a known regexp operator
awk: cmd. line:1: warning: regexp escape sequence `\"' is not a known regexp operator
awk: cmd. line:1: warning: regexp escape sequence `\,' is not a known regexp operator
vCPU                      |  40                        |  0                         |  FAILED
awk: cmd. line:1: warning: regexp escape sequence `\"' is not a known regexp operator
awk: cmd. line:1: warning: regexp escape sequence `\,' is not a known regexp operator
awk: cmd. line:1: warning: regexp escape sequence `\"' is not a known regexp operator
awk: cmd. line:1: warning: regexp escape sequence `\,' is not a known regexp operator
vNet                      |  1                         |  0                         |  FAILED
awk: cmd. line:1: warning: regexp escape sequence `\"' is not a known regexp operator
awk: cmd. line:1: warning: regexp escape sequence `\,' is not a known regexp operator
awk: cmd. line:1: warning: regexp escape sequence `\"' is not a known regexp operator
awk: cmd. line:1: warning: regexp escape sequence `\,' is not a known regexp operator
networkInterface          |  6                         |  0                         |  FAILED
awk: cmd. line:1: warning: regexp escape sequence `\"' is not a known regexp operator
awk: cmd. line:1: warning: regexp escape sequence `\,' is not a known regexp operator
awk: cmd. line:1: warning: regexp escape sequence `\"' is not a known regexp operator
awk: cmd. line:1: warning: regexp escape sequence `\,' is not a known regexp operator
networkSecurityGroups     |  2                         |  0                         |  FAILED
awk: cmd. line:1: warning: regexp escape sequence `\"' is not a known regexp operator
awk: cmd. line:1: warning: regexp escape sequence `\,' is not a known regexp operator
awk: cmd. line:1: warning: regexp escape sequence `\"' is not a known regexp operator
awk: cmd. line:1: warning: regexp escape sequence `\,' is not a known regexp operator
loadBalancers             |  3                         |  0                         |  FAILED
awk: cmd. line:1: warning: regexp escape sequence `\"' is not a known regexp operator
awk: cmd. line:1: warning: regexp escape sequence `\,' is not a known regexp operator
awk: cmd. line:1: warning: regexp escape sequence `\"' is not a known regexp operator
awk: cmd. line:1: warning: regexp escape sequence `\,' is not a known regexp operator
publicIpAddresses         |  3                         |  0                         |  FAILED
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 
failed

**Comment by praveshhibm** [comment]
this issue is addressed in the PR #125 or commit no. 4e89721c57ae0b2b430d710d68fdee1d9ced4c5f . Closing this for now..
