### ISSUE TITLE
Installation Progress option for Client using Script

### ISSUE THREAD

**Issue by skwatra1992** [IBM/cp4d-deployment#70]
I was installing CPD on Azure using Terraform script following this documentation: https://github.com/IBM/cp4d-deployment/blob/master/selfmanaged-openshift/azure/README.md#deployment-topology
When running wsl installation post cpd lite installation using `./wait-for-service-install.sh wsl zen`, the client would like to showcase how much progress (in % or other progress format instead of simply printing "wsl installing!!!!"  shown below) is actually done in the module installation? 

![Screen Shot 2021-04-29 at 3 09 12 PM](https://user-images.githubusercontent.com/15190672/116624531-eb6dd200-a8fc-11eb-84dd-338c307515fc.png)

**Comment by prsahoo** [comment]
We are using CPD-CLI for installation now for CPD 4.5.0 onwards.  It has more descriptive logs which customers can see the progress.   Please find attached sample logs.
[WS_Installation_Logs.txt.zip](https://github.com/IBM/cp4d-deployment/files/9169989/WS_Installation_Logs.txt.zip)

We are closing this issue as Resolved.  For any enhancement to the logs, it will be done in the CPD-CLI.
