### ISSUE TITLE
Warning during 'terraform init' in managed_openshift/ibmcloud

### ISSUE THREAD

**Issue by Ronanb3** [IBM/cp4d-deployment#74]
I have this error message when I run terraform init

`Warning: registry.terraform.io: This version of Terraform has an outdated GPG key and is unable to verify new provider releases. Please upgrade Terraform to at least 0.12.31 to receive new provider updates. For details see: https://discuss.hashicorp.com/t/hcsec-2021-12-codecov-security-event-and-hashicorp-gpg-key-exposure/23512
`

**Comment by praveshcompiles** [comment]
fixed with the recent changes in terraform version to 0.12.31.
