### ISSUE TITLE
[managed-openshift/ibmcloud] CP4D URL is not the right one in the output of the terraform commands

### ISSUE THREAD

**Issue by Ronanb3** [IBM/cp4d-deployment#77]
At the end of the installation script, the output gives the CP4D URL.

In my case it was not the right one.

Here is the output

```
Apply complete! Resources: 30 added, 0 changed, 0 destroyed.
 
Outputs:
 
cpd_url = https://cpd-tenant-cpd-bps2s2.bp2s-test2-cluster-d4c5e211c86b934b94ab6901c8e3e2d5-0000.eu-de.containers.appdomain.cloud/zen
```

The right URL is this one :
https://bps2s2-cpd-bps2s2.bp2s-test2-cluster-d4c5e211c86b934b94ab6901c8e3e2d5-0000.eu-de.containers.appdomain.cloud/

**Comment by praveshcompiles** [comment]
fixed with the 4.0 update
