### ISSUE TITLE
[managed-openshift/ibmcloud] Another error when running 'terraform apply'

### ISSUE THREAD

**Issue by ronanb3** [IBM/cp4d-deployment#78]
I sometimes have this error when running 'terraform apply'

I run 'terraform apply' again and it works fine.

```
Error: Error updating database user (portworxuser) entry: Request failed with status code: 403, ServerErrorResponse: {"errors":"forbidden"}

  on portworx/portworx.tf line 90, in resource "ibm_database" "etcd":
  90: resource "ibm_database" "etcd" {
```

**Comment by prsahoo** [comment]
We dont see this issue anymore with the latest refreshed scripts.  Creation of Cloud Pak for Data cluster on IBM Cloud using Portworx storage is successful.  Closing this issue.  Please re-open if you hit it again.  Thank you.
