### ISSUE TITLE
[managed-openshift/ibmcloud] install cpd-cli in the container

### ISSUE THREAD

**Issue by Ronanb3** [IBM/cp4d-deployment#79]
Hi,
could you install the cpd-cli directly in the container ?

It would help installing modules not available in the actual script and do the upgrades, checks, ...

Here is my commands for instance, the best would it be cpd-cli to be part of the container image.

```
$ sudo podman exec -it bp2s-container-1 bash --login
# cd cpd_install/scripts/
# export TEMPLATES_DIR=~/templates
# export CPD_REGISTRY_PASSWORD="<YOUR_CPD_KEY>”
# ./setup_cpd_cli.sh
# cd $TEMPLATES_DIR/cpd-cli
```

**Comment by praveshcompiles** [comment]
thanks! 
since cpd-cli is not applicable for CPD4.0, I am closing this issue.
