### ISSUE TITLE
[managed-openshift/ibmcloud] Error installing DMC

### ISSUE THREAD

**Issue by LuitasV** [IBM/cp4d-deployment#80]
When you select to install dmc from CP4D in IBM Cloud, the installation never ends, showing allways this massege:
 **dmcaddon-cr is Installing!!!!
module.cpd_install.null_resource.install_dmc[0]: Still creating... [1h30m50s elapsed]
module.cpd_install.null_resource.install_dmc[0]: Still creating... [1h31m0s elapsed]**
and go on

The problem looks like in the script:
**.templates/cpd_install/scripts/install-dmc.sh**, line 51
./check-cr-status.sh dmcaddon dmcaddon-cr ${NAMESPACE} dmcStatus

The correct Status to check, **it is NOT dmcStatus**. The coorect status to check **it is dmcAddonStatus**

**Comment by LuitasV** [comment]
This issue comes from CP4D v4.0 in IBM Cloud.

**Comment by praveshcompiles** [comment]
thanks! this issue has been fixed in PR  #117
