### ISSUE TITLE
[managed-openshift/ibmcloud] Error installing wkc

### ISSUE THREAD

**Issue by LuitasV** [IBM/cp4d-deployment#81]
When you deploy the WKC, looks like the pod **c-db2oltp-wkc-db2u-0** never get ready, and restart again and again. 

Connecting to the pod, could see that the script db2u_entrypoint.sh is registering the db2, applying licence, but the command never ends.
**db2inst1    944      1  0 22:48 pts/0    00:00:00 /bin/bash -x /db2u/db2u_entrypoint.sh
db2inst1   1381    944  0 22:48 pts/0    00:00:00 /mnt/blumeta0/home/db2inst1/sqllib/adm/db2licm -a /db2u/license/db2u-lic**

 I have tried to do it manually with the command db2licm, but the same behavior

Any idea why?

**Comment by praveshcompiles** [comment]
investigating on this issue..

**Comment by LuitasV** [comment]
Have you been able to see anything about this issue, are you able to reproduce it?
If you need any configuration or log, I will send it to you.

Thanks

**Comment by praveshcompiles** [comment]
Hi Luitsav, 
we are still working on it as it is a known issue.. 
for now we have a workaround patch- 
after creating the WKC-CR please run this - 

`NAMESPACE=<zen_namespace>` 
`while [ "$(oc get sts -n ${NAMESPACE} | grep c-db2oltp-wkc-db2u)" = "" ]; do echo "waiting for c-db2oltp-wkc-db2u statefulset."; sleep 60; done
oc patch sts c-db2oltp-wkc-db2u -p='{"spec":{"template":{"spec":{"containers":[{"name":"db2u","tty":false}]}}}}}'; echo "patch for c-db2oltp-wkc-db2u is appied."
`
and then after creating IIS-CR, run this - 

`while [ "$(oc get sts -n ${NAMESPACE} | grep c-db2oltp-iis-db2u)" = "" ]; do echo "waiting for c-db2oltp-iis-db2u statefulset."; sleep 60; done
oc patch sts c-db2oltp-iis-db2u -p='{"spec":{"template":{"spec":{"containers":[{"name":"db2u","tty":false}]}}}}}'; echo "patch for c-db2oltp-iis-db2u is appied."
`

**Comment by LuitasV** [comment]
The workaround patch worked just fine.
Thanks a lot

**Comment by prsahoo** [comment]
Closing the issue.
