### ISSUE TITLE
[managed-openshift/ibmcloud] Problems installing WKC

### ISSUE THREAD

**Issue by LuitasV** [IBM/cp4d-deployment#92]
I am installing CP4D on ROKS, when it gets to the WKC installation part, the installation never finishes, always giving the same message.
_**module.cpd[0].null_resource.install_wkc[0]: Still creating... [3h46m14s elapsed]
module.cpd[0].null_resource.install_wkc[0] (local-exec): Installing wkc-cr - Status: InProgress !!!!**_

I have checked the pods, and it seems that the c-db2oltp-wkc-db2u-0 pod starts and stops continuously, after giving an error.
Running a describe of the pod, I get the following event back:
**_Events:
  Type     Reason           Age   From               Message
  ----     ------           ----  ----               -------
  Normal   Scheduled        2s    default-scheduler  Successfully assigned zen/c-db2oltp-wkc-db2u-0 to 10.240.0.10
  Warning  SysctlForbidden  3s    kubelet            forbidden sysctl: "kernel.shmmni" not whitelisted_**

Reviewing the YAML of the StatefulSet, I check that the following security context configuration has been included:
**_sysctls:
          - name: kernel.shmmni
            value: '3072'
          - name: kernel.shmmax
            value: '12884901888'
          - name: kernel.shmall
            value: '6291456'
          - name: kernel.sem
            value: 250 768000 100 3072
          - name: kernel.msgmni
            value: '12288'
          - name: kernel.msgmax
            value: '65536'
          - name: kernel.msgmnb
            value: '65536'_**

I imagine that the error is that sysctl are not whitelisted by the OpenShift Container Platform. How can i fix this issue to continue with the installation?

Thanks in advance

**Comment by LuitasV** [comment]
Looks like for the documentation, that the commenting in parameters "...kernel_params", must be uncomment, if you use portworx as storage in ROKS.
https://www.ibm.com/support/producthub/icpdata/docs/content/SSQNUZ_latest/svc-wkc/wkc-install.html
But everytime you lauch the terraform apply, the yaml file in wkc_cr.yaml, it recreates always with the commenting part.

**Comment by praveshcompiles** [comment]
Hi @LuitasV , 
that's right.. Can you please delete the existing WKC service and re-install with the new CR with the two parameters set. 
I am investigating on why the Yaml didn't have that flag on for ROKS.

**Comment by LuitasV** [comment]
Hi @praveshcompiles ,
Yes, I tested it, and it works. But I had to delete the previous WKC installation first. Looks like, if you are installing in ibmcloud, it is necessary to uncomment that parameters in the wkc_cr.yaml.

**Comment by prsahoo** [comment]
Thanks for confirming that it works now. Closing the issue.  Please feel free to reopen if you encounter issues again. Thank you.
