### ISSUE TITLE
WKC installation run forever 

### ISSUE THREAD

**Issue by fqueau** [IBM/cp4d-deployment#93]
WKC 4.02 installation never finished with the following message : 
module.cpd[0].null_resource.install_wkc[0]: Still creating... [17h11m4s elapsed]
module.cpd[0].null_resource.install_wkc[0] (local-exec): State - 1/1 1/1 1/1 1/1 1/1 1/1 1/1 1/1 1/1 1/1 1/1 1/1 1/1 1/1 1/1 1/1 1/1 1/1 1/1 0/1, podstatus - Running Running Running Running Running Running Running Running Running Running Running Running Running Running Running Running Running Running Running Completed
module.cpd[0].null_resource.install_wkc[0]: Still creating... [17h11m14s elapsed]
module.cpd[0].null_resource.install_wkc[0] (local-exec):  is starting
module.cpd[0].null_resource.install_wkc[0] (local-exec): State - 1/1 1/1 1/1 1/1 1/1 1/1 1/1 1/1 1/1 1/1 1/1 1/1 1/1 1/1 1/1 1/1 1/1 1/1 1/1 0/1, podstatus - Running Running Running Running Running Running Running Running Running Running Running Running Running Running Running Running Running Running Running Completed
module.cpd[0].null_resource.install_wkc[0]: Still creating... [17h11m24s elapsed]
module.cpd[0].null_resource.install_wkc[0] (local-exec):  is starting
module.cpd[0].null_resource.install_wkc[0] (local-exec): State - 1/1 1/1 1/1 1/1 1/1 1/1 1/1 1/1 1/1 1/1 1/1 1/1 1/1 1/1 1/1 1/1 1/1 1/1 1/1 0/1, podstatus - Running Running Running Running Running Running Running Running Running Running Running Running Running Running Running Running Running Running Running Completed
module.cpd[0].null_resource.install_wkc[0]: Still creating... [17h11m34s elapsed]
^CInterrupt received.
Please wait for Terraform to exit or data loss may occur.
Gracefully shutting down...
Stopping operation...

**Comment by maulikshah999** [comment]
@fqueau Which cloud provider is being used AWS/Azure or IBM Cloud? Are you using self-managed or managed openshift?

**Comment by fqueau** [comment]
Hi that was on ROKS (so IBM Cloud with Managed openshift). 

was this fixed with CP4 D 4.0.3 ? 

Thanks. 
_________________________________________________________
Frank Quéau
Software Technical Architect for BNPP / BPCE.
IBM Cloud and Cognitive Software
17 Avenue de l'Europe, Bois Colombes Cedex, 92275 France+33685035216 
(mobile) 

Compagnie IBM France
Siège Social : 17, avenue de l'Europe, 92275 Bois-Colombes Cedex
RCS Nanterre 552 118 465
Forme Sociale : S.A.S.
Capital Social : 663.265.053 €
SIRET : 552 118 465 03644 - Code NAF 6203Z





From:   "Maulik Shah" ***@***.***>
To:     "IBM/cp4d-deployment" ***@***.***>
Cc:     "fqueau" ***@***.***>, "Mention" 
***@***.***>
Date:   06/12/2021 23:50
Subject:        [EXTERNAL] Re: [IBM/cp4d-deployment] WKC installation run 
forever  (Issue #93)



@fqueau Which cloud provider is being used AWS/Azure or IBM Cloud? Are you 
using self-managed or managed openshift? — You are receiving this because 
you were mentioned. Reply to this email directly, view it on GitHub, or 
unsubscribe ‍
@fqueau Which cloud provider is being used AWS/Azure or IBM Cloud? Are you 
using self-managed or managed openshift?
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 


Sauf indication contraire ci-dessus:/ Unless stated otherwise above:
Compagnie IBM France
Siège Social : 17 avenue de l'Europe, 92275 Bois-Colombes Cedex
RCS Nanterre 552 118 465
Forme Sociale : S.A.S.
Capital Social : 657.364.587 €
SIREN/SIRET : 552 118 465 03644 - Code NAF 6202A

**Comment by maulikshah999** [comment]
@fqueau Can you please try again with the latest supported version? It should be fixed on the `4.0.5` version.

**Comment by prsahoo** [comment]
This is fixed. WKC installation is successful using CPD version 4.0.5.  Closing the issue.  Please feel free to reopen if you still encounter any issue. Thank you.
