### ISSUE TITLE
caserviceinstances.ca.cpd.ibm.com CR failure

### ISSUE THREAD

**Issue by Reggith** [IBM/cp4d-deployment#94]
I see that using the existing-deployment method to install Cognos, everything looks fine within CPD and it shows Cognos service as available. However, when I look at the CRDs within the OCP GUI; one of them being caserviceinstances.ca.cpd.ibm.com, the instances section shows ca1637786093320873-cr. If I click on that I see an error "All items completed
The playbook has failed. See earlier output for exact error" Attached screenshot for the same. The other CR CAService is fine.
<img width="1098" alt="Screen Shot 2021-11-25 at 8 33 14 am" src="https://user-images.githubusercontent.com/94423208/143315496-b8c27490-03cd-4ac1-bedb-b16280b0efc8.png">

**Comment by prsahoo** [comment]
CA service installation is passing now successfully.  Closing the issue.  Please feel free to reopen the issue if you hit any issues.  Thank you.
