### ISSUE TITLE
Installation on IBM Roks not working with this error message related to 

### ISSUE THREAD

**Issue by fqueau** [IBM/cp4d-deployment#96]
odule.portworx.null_resource.volume_attachment[2]: Provisioning with 'local-exec'...
module.portworx.null_resource.volume_attachment[3]: Provisioning with 'local-exec'...
module.portworx.null_resource.volume_attachment[2] (local-exec): Executing: ["/bin/bash" "-c" "#!/bin/bash\n\n# Before creating, check to see if attachment for volume is already present\nif ! RESPONSE=$(curl -s -X GET \\\n        -H \"Authorization: $TOKEN\" \\\n        -H \"Content-Type: application/json\" \\\n        -H \"X-Auth-Resource-Group-ID: $RESOURCE_GROUP_ID\" \\\n        \"https://$REGION.containers.cloud.ibm.com/v2/storage/getAttachments?cluster=$CLUSTER_ID&worker=$WORKER_ID\"\n); then\n  echo \"Error when trying to /getAttachments\"\n  exit 1\nfi\n\nID=$(echo $RESPONSE | jq -r --arg VOLUMEID \"$VOLUME_ID\" '.volume_attachments[] | select(.volume.id==$VOLUMEID) | .id')\n\n# If should create attachment, create attachment\nif [ \"$ID\" == \"\" ] || [ \"$ID\" == \"null\" ]; then\n    if ! RESPONSE=$(\n        curl -s -X POST -H \"Authorization: $TOKEN\" \\\n            \"https://$REGION.containers.cloud.ibm.com/v2/storage/vpc/createAttachment?cluster=$CLUSTER_ID&worker=$WORKER_ID&volumeID=$VOLUME_ID\" -d '{}'\n    ); then\n      echo \"Error when trying to /createAttachment\"\n      exit 1\n    fi\n\n    ID=$(echo $RESPONSE | jq -r .id)\n\n    if [ \"$ID\" == \"\" ] || [ \"$ID\" == \"null\" ]; then\n        echo \"/createAttachment did not work: $RESPONSE\"\n        exit 1\n    fi\n    echo \"Created attachment for $CLUSTER_ID, $WORKER_ID and $VOLUME_ID: $ID\"\n    echo 'Sleeping for 1 minute...'\n    sleep 1m # it takes some seconds for the attachment to stabilize and propagate\nelse\n  echo \"Attachment already exists: $RESPONSE\"\nfi\n"]
module.portworx.null_resource.volume_attachment[3] (local-exec): Executing: ["/bin/bash" "-c" "#!/bin/bash\n\n# Before creating, check to see if attachment for volume is already present\nif ! RESPONSE=$(curl -s -X GET \\\n        -H \"Authorization: $TOKEN\" \\\n        -H \"Content-Type: application/json\" \\\n        -H \"X-Auth-Resource-Group-ID: $RESOURCE_GROUP_ID\" \\\n        \"https://$REGION.containers.cloud.ibm.com/v2/storage/getAttachments?cluster=$CLUSTER_ID&worker=$WORKER_ID\"\n); then\n  echo \"Error when trying to /getAttachments\"\n  exit 1\nfi\n\nID=$(echo $RESPONSE | jq -r --arg VOLUMEID \"$VOLUME_ID\" '.volume_attachments[] | select(.volume.id==$VOLUMEID) | .id')\n\n# If should create attachment, create attachment\nif [ \"$ID\" == \"\" ] || [ \"$ID\" == \"null\" ]; then\n    if ! RESPONSE=$(\n        curl -s -X POST -H \"Authorization: $TOKEN\" \\\n            \"https://$REGION.containers.cloud.ibm.com/v2/storage/vpc/createAttachment?cluster=$CLUSTER_ID&worker=$WORKER_ID&volumeID=$VOLUME_ID\" -d '{}'\n    ); then\n      echo \"Error when trying to /createAttachment\"\n      exit 1\n    fi\n\n    ID=$(echo $RESPONSE | jq -r .id)\n\n    if [ \"$ID\" == \"\" ] || [ \"$ID\" == \"null\" ]; then\n        echo \"/createAttachment did not work: $RESPONSE\"\n        exit 1\n    fi\n    echo \"Created attachment for $CLUSTER_ID, $WORKER_ID and $VOLUME_ID: $ID\"\n    echo 'Sleeping for 1 minute...'\n    sleep 1m # it takes some seconds for the attachment to stabilize and propagate\nelse\n  echo \"Attachment already exists: $RESPONSE\"\nfi\n"]
module.portworx.null_resource.volume_attachment[5]: Provisioning with 'local-exec'...
module.portworx.null_resource.volume_attachment[5] (local-exec): Executing: ["/bin/bash" "-c" "#!/bin/bash\n\n# Before creating, check to see if attachment for volume is already present\nif ! RESPONSE=$(curl -s -X GET \\\n        -H \"Authorization: $TOKEN\" \\\n        -H \"Content-Type: application/json\" \\\n        -H \"X-Auth-Resource-Group-ID: $RESOURCE_GROUP_ID\" \\\n        \"https://$REGION.containers.cloud.ibm.com/v2/storage/getAttachments?cluster=$CLUSTER_ID&worker=$WORKER_ID\"\n); then\n  echo \"Error when trying to /getAttachments\"\n  exit 1\nfi\n\nID=$(echo $RESPONSE | jq -r --arg VOLUMEID \"$VOLUME_ID\" '.volume_attachments[] | select(.volume.id==$VOLUMEID) | .id')\n\n# If should create attachment, create attachment\nif [ \"$ID\" == \"\" ] || [ \"$ID\" == \"null\" ]; then\n    if ! RESPONSE=$(\n        curl -s -X POST -H \"Authorization: $TOKEN\" \\\n            \"https://$REGION.containers.cloud.ibm.com/v2/storage/vpc/createAttachment?cluster=$CLUSTER_ID&worker=$WORKER_ID&volumeID=$VOLUME_ID\" -d '{}'\n    ); then\n      echo \"Error when trying to /createAttachment\"\n      exit 1\n    fi\n\n    ID=$(echo $RESPONSE | jq -r .id)\n\n    if [ \"$ID\" == \"\" ] || [ \"$ID\" == \"null\" ]; then\n        echo \"/createAttachment did not work: $RESPONSE\"\n        exit 1\n    fi\n    echo \"Created attachment for $CLUSTER_ID, $WORKER_ID and $VOLUME_ID: $ID\"\n    echo 'Sleeping for 1 minute...'\n    sleep 1m # it takes some seconds for the attachment to stabilize and propagate\nelse\n  echo \"Attachment already exists: $RESPONSE\"\nfi\n"]
module.portworx.null_resource.volume_attachment[4]: Still creating... [10s elapsed]
module.portworx.null_resource.volume_attachment[2]: Still creating... [10s elapsed]
module.portworx.null_resource.volume_attachment[1]: Still creating... [10s elapsed]
module.portworx.null_resource.volume_attachment[3]: Still creating... [10s elapsed]
module.portworx.null_resource.volume_attachment[5]: Still creating... [10s elapsed]
module.portworx.null_resource.volume_attachment[1] (local-exec): /createAttachment did not work: {"incidentID":"527b1e71-9449-4117-9cb5-d09153262e76","code":"P4050","description":"The 'vpc-gen2' infrastructure operation failed with the message: volume r010-6c0ccf54-3a41-48f1-a9f5-d876de23eebc is in use","type":"BadRequest"}

module.portworx.null_resource.volume_attachment[4] (local-exec): /createAttachment did not work: {"incidentID":"a39f8ce3-7eca-464a-a105-b2e2ee742090","code":"P4050","description":"The 'vpc-gen2' infrastructure operation failed with the message: volume r010-04925ed3-7ecb-487d-a98b-9c4af5d17aec is in use","type":"BadRequest"}

module.portworx.null_resource.volume_attachment[3] (local-exec): /createAttachment did not work: {"incidentID":"a520599d-0f2b-472c-b861-2a13218e6062","code":"P4050","description":"The 'vpc-gen2' infrastructure operation failed with the message: volume r010-6781dda4-3526-41df-a568-d782e2de2d8a is in use","type":"BadRequest"}

module.portworx.null_resource.volume_attachment[2] (local-exec): /createAttachment did not work: {"incidentID":"d480ead8-179d-4b7b-8a71-5f817246a52c","code":"P4050","description":"The 'vpc-gen2' infrastructure operation failed with the message: volume r010-26ae10c3-f779-48cd-a711-f3e980627494 is in use","type":"BadRequest"}

module.portworx.null_resource.volume_attachment[5] (local-exec): /createAttachment did not work: {"incidentID":"c488d870-97a7-44d2-a50a-5b9b3cbdff93","code":"P4050","description":"The 'vpc-gen2' infrastructure operation failed with the message: volume r010-70a0e8e0-9a2d-4c0e-9a3e-31c9b653421a is in use","type":"BadRequest"}

Error: Error running command '#!/bin/bash

# Before creating, check to see if attachment for volume is already present
if ! RESPONSE=$(curl -s -X GET \
        -H "Authorization: $TOKEN" \
        -H "Content-Type: application/json" \
        -H "X-Auth-Resource-Group-ID: $RESOURCE_GROUP_ID" \
        "https://$REGION.containers.cloud.ibm.com/v2/storage/getAttachments?cluster=$CLUSTER_ID&worker=$WORKER_ID"
); then
  echo "Error when trying to /getAttachments"
  exit 1
fi

ID=$(echo $RESPONSE | jq -r --arg VOLUMEID "$VOLUME_ID" '.volume_attachments[] | select(.volume.id==$VOLUMEID) | .id')

# If should create attachment, create attachment
if [ "$ID" == "" ] || [ "$ID" == "null" ]; then
    if ! RESPONSE=$(
        curl -s -X POST -H "Authorization: $TOKEN" \
            "https://$REGION.containers.cloud.ibm.com/v2/storage/vpc/createAttachment?cluster=$CLUSTER_ID&worker=$WORKER_ID&volumeID=$VOLUME_ID" -d '{}'
    ); then
      echo "Error when trying to /createAttachment"
      exit 1
    fi

    ID=$(echo $RESPONSE | jq -r .id)

    if [ "$ID" == "" ] || [ "$ID" == "null" ]; then
        echo "/createAttachment did not work: $RESPONSE"
        exit 1
    fi
    echo "Created attachment for $CLUSTER_ID, $WORKER_ID and $VOLUME_ID: $ID"
    echo 'Sleeping for 1 minute...'
    sleep 1m # it takes some seconds for the attachment to stabilize and propagate
else
  echo "Attachment already exists: $RESPONSE"
fi
': exit status 1. Output: /createAttachment did not work: {"incidentID":"c488d870-97a7-44d2-a50a-5b9b3cbdff93","code":"P4050","description":"The 'vpc-gen2' infrastructure operation failed with the message: volume r010-70a0e8e0-9a2d-4c0e-9a3e-31c9b653421a is in use","type":"BadRequest"}

**Comment by prsahoo** [comment]
We dont see this issue anymore with the latest refreshed scripts. Creation of Cloud Pak for Data cluster on IBM Cloud using Portworx storage is successful. Closing this issue. Please re-open if you hit it again. Thank you.
